import time
import unittest
from unittest.mock import MagicMock, patch

import pytest

from src.core.models.service_dto import Ticker
from src.core.models.trade import TradePair
from src.infrastructure.system_manager import SystemManager


@pytest.mark.integration
@pytest.mark.slow
class TestSystemDataFlow(unittest.TestCase):
    """
    End-to-End Integration Test (Data Flow Focus)
    Verifies that the multi-threaded pipeline infrastructure (WS -> Collector -> Processor -> SignalGen)
    is sound, without relying on specific non-deterministic trading outcomes.
    """

    @patch("src.infrastructure.system_manager.SystemManager._set_up_telegram_bot")
    @patch("src.infrastructure.system_manager.SystemManager._construct_ws_interface")
    @patch("src.infrastructure.system_manager.SystemManager._construct_binance_future")
    def test_pipeline_pulse(self, mock_binance, mock_ws, mock_telegram):
        # 1. Setup Mocked Network Interfaces
        mock_telegram.return_value = MagicMock()
        mock_binance.return_value = MagicMock()

        # We need to simulate the WebSocketInterface so we can manually trigger the callbacks
        # that the brokers would normally trigger when data arrives over the internet.
        mock_ws_instance = MagicMock()
        mock_ws.return_value = mock_ws_instance

        # 2. Boot up the entire system in Dry Run mode
        # Silence heartbeat threads to prevent I/O closed file errors on teardown
        with (
            patch("src.trading.trade_manager.TradeManager._thread_log_status"),
            patch("src.trading.signal_generator.SignalGenerator._thread_log_status"),
            patch("src.strategy.strategy_manager.StrategyManager._thread_log_status"),
        ):
            sm = SystemManager(disable_trade=True)

            # 3. Simulate WebSocket Connection
            # Retrieve the callbacks that the DataManager registered to the WS interface
            ticker_callback = None
            for call in mock_ws_instance.ticker.call_args_list:
                if "callback" in call.kwargs:
                    ticker_callback = call.kwargs["callback"]
                    break

            self.assertIsNotNone(
                ticker_callback,
                "DataManager did not register a ticker callback with WebSocketInterface",
            )

            # 4. Inject a pulse of data (Simulating market activity)
            trade_pair = TradePair("BTC", "USDT")
            start_ts = int(time.time() * 1000)

            for i in range(15):
                fake_ticker = Ticker(
                    timestamp=start_ts + (i * 1000),  # 1s intervals
                    source="MOCK_BINANCE",
                    ticker=trade_pair,
                    price=60000.0 + i,
                )
                ticker_callback(fake_ticker)
                time.sleep(0.05)

            # 5. Verify Data Flow
            with sm.data_manager.collector.lock_price_data:
                df_size = sm.data_manager.collector.price_data.shape[0]
                self.assertGreater(
                    df_size,
                    0,
                    "DataCollector failed to process WS queue into DataFrame",
                )

            time.sleep(1.0)

            self.assertIsNotNone(
                sm.signal_generator.indicators,
                "SignalGenerator failed to receive data from DataPipeline",
            )
            self.assertIn(
                "PRICE",
                [k.name for k in sm.signal_generator.indicators],
                "PRICE indicator was not generated by DataProcessor",
            )

            # 6. Graceful Teardown
            sm.stop()
            sm.trade_manager.stop()
            time.sleep(0.5)


if __name__ == "__main__":
    unittest.main()
